s,\([ ]\)Char\([ ]\),\1char\2,
s,^Char\([ ]\),char\1,
s,\([ ]\)Char,\1char,
s,\([ ]\)Vint\([ ]\),\1int\2,
s,Vint\([ ]\),int\1,
s,\([ ]\)Vint$,\1int,
s,\([ ]\)Int\([ ]\),\1long\2,
s,Int\([ ]\),long\1,
s,\([ ]\)Int$,\1long,
s,\([ ]\)Bool\([ ]\),\1char\2,
s,Bool\([ ]\),char\1,
s,\([ ]\)Bool$,\1char,
s,\([ ]\)Quot\([ ]\),\1int\2,
s,Quot\([ ]\),int\1,
s,\([ ]\)Quot$,\1int,
s,\([ ]\)Set\([ ]\),\1unsigned long\2,
s,Set\([ ]\),\1unsignedong\1,
s,\([ ]\)Set\([ ]$igned long,
s,\([ ]\)Time\([ ]\),\1long\2,
s,Time\([ ]\),long\1,
s,\([ ]\)Time$,\1long,
s,\([ ]\)Id\([ ]\),\1int\2,
s,Id\([ ]\),int\1,
s,\([ ]\)Id$,\1int,

