#!/bin/ksh

#
#			Uses parameter BuildLabel

# I N C O M P L E T E


while expr "$1" : "-[a-z]" > /dev/null ; do

 if   test "$1" = "-q" ; then
   shift 1
 elif test "$1" = "-f" ; then
   shift 1
   fonly=1
 elif test "$1" = "-o" ; then
   owner=$2
   shift 2
 else
   echo 'orash -f file'
   echo ' -f -- fields only'
   break;
 fi

done

bl=${BuildLabel}
if test "$bl" != "" ; then
  bl="-v\"$bl\""
fi


