#!/bin/ksh

fonly=
owner='YMODAPP'
blksz=8
atdb=

while expr "$1" : "-[qfoab]" > /dev/null ; do

 if   test "$1" = "-q" ; then
   shift 1
 elif test "$1" = "-f" ; then
   shift 1
   fonly=1
 elif test "$1" = "-o" ; then
   owner=$2
   shift 2
 elif test "$1" = "-a" ; then
   atdb="@cobra"
   test "$owner" = "YMODAPP" && owner='YM01'
   shift 1
 elif test "$1" = "-b" ; then
   blksz=$2
   shift 2
 else
   echo 'oot {-q} {-f} {-o owner} {-b blksz} file'
   echo ' -f -- fields only'
   break;
 fi

done

colmn=$1

 colmn=`echo $colmn | tr "[a-z]" "[A-Z]"`

cat <<EOF | sqlplus -s / | sed -e '/^$/d'

set linesize 1000;
set pagesize 10000;

column column_name fold_before

break on column_name skip 1;

select substr(tc.table_name || '   ' || nvl(at.tablespace_name,'?') ||
  '('||nvl(at.blocks,-1)*$blksz ||')'  ||'('||nvl(at.num_rows,-1)||')'
				       ||'('||nvl(at.avg_space,-1)||')'
					, 0, 52) table_name,
       substr('   '||tc.column_id||' '|| tc.column_name, 0, 24) column_name, 
       substr(decode(tc.data_type,'VARCHAR2','VCHAR2',tc.data_type), 0,6) type,
       tc.data_length,
       ai.index_name||decode(nvl(ai.uniqueness, ' '), 'UNIQUE', '  U', 'NONUNIQUE', ' NU', '') k
from all_tab_columns$atdb tc, all_ind_columns$atdb ic, 
     all_indexes$atdb ai, all_tables$atdb at
where tc.owner = ic.table_owner(+)
 and  tc.table_name = ic.table_name(+)
 and  tc.column_name = ic.column_name(+)
 and  ic.table_owner = ai.table_owner(+)
 and  ic.table_name = ai.table_name(+)
 and  ic.index_owner = ai.owner(+)
 and  ic.index_name = ai.index_name(+)
 and  at.owner(+) = tc.owner
 and  at.table_name(+) = tc.table_name
 and (tc.owner='$owner'
  or  tc.owner='SYS')
 and  tc.column_name='$colmn'
order by table_name, tc.column_id;

EOF

