#!/bin/ksh

as=all_source

user=misapp/password
#user=/

while expr "$1" : "-[aq]" > /dev/null ; do

 if   test "$1" = "-q" ; then
   shift 1
 elif test "$1" = "-a" ; then
   shift 1
   as=dba_all_source
 else
   echo 'oop file'
   break;
 fi

done


proc=
if test "$1" != "" ; then
 proc="where name='$1'" 
fi

proc=`echo $proc | tr "[a-z]" "[A-Z]"`

cat <<EOF | sqlplus -s $user

set linesize 1000;
set pagesize 10000;

set arraysize 4;

select text
from $as 
$proc order by name,line;

select text
from ${as}@cobra
$proc order by name,line;

EOF
