#!/bin/ksh

fonly=
owner='MISAPP'
blksz=8
atdb=



if test "X$ORA_SCHEMA" = "X"; then
 #ORA_SCHEMA=misapp/password
 ORA_SCHEMA=/
fi

if test "$ORACLE_HOME" = "" ; then
  ORACLE_HOME=/opt/oracle/8.1.6.3
fi


while expr "$1" : "-[a-z]" > /dev/null ; do

 if   test "$1" = "-q" ; then
   shift 1
 elif test "$1" = "-f" ; then
   shift 1
   fonly=1
 elif test "$1" = "-o" ; then
   owner=$2
   shift 2
 elif test "$1" = "-a" ; then
   atdb="@cobra"
   test "$owner" = "YMODAPP" && owner='YM01'
   shift 1
 elif test "$1" = "-b" ; then
   blksz=$2
   shift 2
 elif test "$1" = "-u" ; then
   ORA_SCHEMA=$2
   shift 2
 else
   echo 'oosch {-q} {-f} {-o owner} {-b blksz} file'
   echo ' -f -- fields only'
   exit 1;
 fi

done

table=$1
if test "$table" != "" ; then
					# Table specified

 table=`echo $table | tr "[a-z]" "[A-Z]"`

cat <<EOF | sqlplus -s $ORA_SCHEMA | sed -e '/^$/d;s.,0)..'

set linesize 1000;
set pagesize 0;
set head off;
set feedback off
set pause off
set echo off

column column_name fold_before;

break on table_name skip 1;

select decode(tc.column_id, 1, decode(rownum,1,'',');')||'create table ', ','),
       tc.table_name,   decode(tc.column_id, 1, '(', ''),
       tc.column_name,
       substr(tc.data_type,1,10) data_type,
       decode(tc.data_precision, null,
               '('||substr(tc.data_length,1,4) || ')',
               '('||substr(tc.data_precision,1,4) || ',' ||
                    substr(tc.data_scale,1,2)   || ')') lp,
       decode(tc.nullable, 'N', 'NOT NULL', '')
from all_tab_columns$atdb tc,
     all_tables$atdb at
where
      at.owner(+) = tc.owner
 and  at.table_name(+) = tc.table_name
 and (tc.owner='$owner'
  or  tc.owner='SYS')
 and  tc.table_name='$table'
order by table_name, tc.column_id;

EOF
echo ');'

if test "$fonly" = "" ; then
 
cat <<EOF | sqlplus -s $ORA_SCHEMA | sed -e '/^$/d'

set linesize 1000;
set pagesize 0;
set head off;
set feedback off
set pause off
set echo off

column column_name fold_before;

break on table_index skip 1;

select decode(ic.column_position,
        1,decode(rownum,1,'',');')||'create '||ix.uniqueness||' index '||ic.index_name||' ', 
          ''),
       decode(ic.column_position, 1, ' on '||ic.table_name||'(', ','),
       substr(ic.column_name, 0, 26) column_name,
       decode(ic.descend, 'ASC', '', ic.descend)
from all_ind_columns$atdb ic, all_indexes$atdb ix
where ix.table_owner = ic.table_owner
 and  ix.table_name  = ic.table_name
 and  ix.owner       = ic.index_owner
 and  ix.index_name  = ic.index_name
 and  ic.index_owner = '$owner'
 and  ic.table_name = '$table'
order by ic.index_name, ic.index_owner, ic.table_owner, ic.column_position;

EOF
echo ');'
fi

else
					# Table not specified

cat <<EOF | sqlplus -s $ORA_SCHEMA | sed -e '/^$/d'

set linesize 1000;
set pagesize 10000;

column table_name fold_before
column cid noprint;

break on table_name skip 1;

select decode(tc.column_id, 1, decode(rownum,1,'',');')||'create table ', ','),
       tc.table_name,   decode(tc.column_id, 1, '(', ''),
       tc.column_name,
       substr(tc.data_type,1,10) data_type,
       decode(tc.data_precision, null,
               '('||substr(tc.data_length,1,4) || ')',
               '('||substr(tc.data_precision,1,4) || ',' ||
                    substr(tc.data_scale,1,2)   || ')') lp,
       decode(tc.nullable, 'N', 'NOT NULL', '')
from all_tab_columns$atdb tc,
     all_tables$atdb at
where
      at.owner(+) = tc.owner
 and  at.table_name(+) = tc.table_name
 and (tc.owner='$owner'
  or  tc.owner='SYS')
order by table_name, tc.column_id;

EOF

if test "$fonly" = "" ; then
 
cat <<EOF | sqlplus -s $ORA_SCHEMA | sed -e '/^$/d'

set linesize 1000;
set pagesize 10000;

column uq fold_before

break on table_index skip 1;


set linesize 1000;
set pagesize 0;
set head off;
set feedback off
set pause off
set echo off

column column_name fold_before;

break on table_index skip 1;

select decode(ic.column_position,
        1,decode(rownum,1,'',');'||chr(13))||'create '||ix.uniqueness||' index '||ic.index_name||' ', 
          ''),
       decode(ic.column_position, 1, ' on '||ic.table_name||'(', ','),
       substr(ic.column_name, 0, 26) column_name,
       decode(ic.descend, 'ASC', '', ic.descend)
from all_ind_columns$atdb ic, all_indexes$atdb ix
where ix.table_owner = ic.table_owner
 and  ix.table_name  = ic.table_name
 and  ix.owner       = ic.index_owner
 and  ix.index_name  = ic.index_name
 and  ic.index_owner = '$owner'
order by ic.index_name, ic.index_owner, ic.table_owner, ic.column_position;

EOF

fi
fi

