#!/bin/ksh

fonly=
blksz=8
owner='MISAPP'
tscond=

if test "X$ORA_SCHEMA" = "X"; then
 #ORA_SCHEMA=misapp/password
 ORA_SCHEMA=/
fi

while expr "$1" : "-[qfos]" > /dev/null ; do

 if   test "$1" = "-q" ; then
   shift 1
 elif test "$1" = "-f" ; then
   shift 1
   fonly=1
 elif test "$1" = "-o" ; then
   owner=$2
   shift 2
 elif test "$1" = "-s" ; then
   tscond="tablespace_name = '$2' and"
   shift 2
 elif test "$1" = "-b" ; then
   blksz=$2
   shift 2
 else
   echo 'oos -f table'
   echo ' -f          -- fields only'
   echo ' -o <owner>  -- owner'
   echo ' -s <tsname> -- tablespace name'
   break;
 fi

done

table=$1
if test "$table" != "" ; then
					# Table specified

 table=`echo $table | tr "[a-z]" "[A-Z]"`

cat <<EOF | sqlplus -s $ORA_SCHEMA | sed -e '/^$/d'

set linesize 1000;
set pagesize 10000;

column column_name fold_before

break on table_name skip 1;

select substr(tc.table_name || '   ' || at.tablespace_name ||'('||at.blocks*$blksz ||')', 0, 44) table_name,
       substr('   '||tc.column_id||' '|| tc.column_name, 0, 21) column_name, 
       substr(decode(tc.data_type,'VARCHAR2','VCHAR2',tc.data_type), 0,6) type,
       ai.index_name||decode(nvl(ai.uniqueness, ' '), 'UNIQUE', '  U', 'NONUNIQUE', ' NU', '') k
from all_tab_columns tc, all_ind_columns ic, all_indexes ai, all_tables at
where tc.owner = ic.table_owner(+)
 and  tc.table_name = ic.table_name(+)
 and  tc.column_name = ic.column_name(+)
 and  ic.table_owner = ai.table_owner(+)
 and  ic.table_name = ai.table_name(+)
 and  ic.index_owner = ai.owner(+)
 and  ic.index_name = ai.index_name(+)
 and  at.owner = tc.owner
 and  at.table_name = tc.table_name
 and (tc.owner='$owner'
  or  tc.owner='SYS')
 and  tc.table_name='$table'
order by table_name;

EOF

if test "$fonly" = "" ; then
 
cat <<EOF | sqlplus -s $ORA_SCHEMA

set linesize 1000;
set pagesize 10000;

break on table_index skip 1;

select substr(ic.table_name||'..'||ic.index_name, 0, 40) table_index,
       ix.leaf_blocks*$blksz blocks,
       decode(ix.uniqueness, 'UNIQUE', 'UQ', 'NONUNIQUE', 'NU') uq,
       substr(ic.column_name, 0, 26) column_name
from all_ind_columns ic, all_indexes ix
where ix.table_owner = ic.table_owner
 and  ix.table_name  = ic.table_name
 and  ix.owner       = ic.index_owner
 and  ix.index_name  = ic.index_name
 and  ic.index_owner = '$owner'
 and  ic.table_name = '$table'
order by table_index, ic.index_owner, ic.table_owner, ic.column_position;

EOF
fi

else
					# Table not specified

cat <<EOF | sqlplus -s $ORA_SCHEMA | sed -e '/^$/d'

set linesize 1000;
set pagesize 10000;

break on Report;

compute sum of blocks on Report;

select 
       at.table_name, 
       substr(at.tablespace_name,0,15) tablespace_name,
       at.blocks*$blksz blocks
--      ,0 a,
--       0 b
from all_tables at
where   $tscond
	at.owner='$owner'
union
select 
       at.table_name, 
       substr(at.tablespace_name,0,15) tablespace_name,
       at.leaf_blocks*$blksz blocks
--      ,at.avg_leaf_blocks_per_key a,
--       at.avg_data_blocks_per_key b
from all_indexes at
where  $tscond
       at.owner='$owner'
order by table_name;

EOF

fi

