CC = \c600\bin\cl
LK = \c600\bin\link
CFLAGS = /Zi /AL
LFLAGS = /B /NOI /CODEV
#CFLAGS = /AL /Ocegilsa /Gs
#LFLAGS = /B /NOI


all: map.exe

map.exe: ../map.c
	$(CC) $(CFLAGS) -I. -o map.exe ../map.c

